BUG: Fix loading of DICOM series removing unneeded "slicer.util.unicodeify"
It fixes the following error reported when loading RTImage dataset while
having the SlicerRT modules loaded:

  Traceback (most recent call last):
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 730, in getLoadablesFromFileLists
      loadablesByPlugin[plugin] = plugin.examineForImport(fileLists)
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 147, in examineForImport
      loadables.sort(key=cmp_to_key(lambda x,y: self.seriesSorter(x,y)))
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 147, in <lambda>
      loadables.sort(key=cmp_to_key(lambda x,y: self.seriesSorter(x,y)))
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 268, in seriesSorter
      xNumber = int(xName[:xName.index(':')])
  TypeError: a bytes-like object is required, not 'str'
  Warning: Plugin failed: DICOMScalarVolumePlugin


Since Python3 handle all strings as unicode, this commit removes the
unicodeify function originally introduced in these commits:
* r23472 (BUG: 3688 unicode characters from dicom)
* r23473 (BUG: unicodeify date to fix subject hierarchy)
* r23483 (BUG: Fixed accented character display of series and studies in subject)
* r23484 (STYLE: Removed testing code from previous commit)

Dataset originally associated with issue 3688 is loading as expected.