BUG: Fix indentation issue in TemplateManager.py
This commit fixes a regression introduced in r24452 (BUG: Fixed extension
creation in version-controlled repository).

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jcfr/Projects/Slicer-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/ExtensionWizard.py", line 7, in <module>
    import SlicerWizard.ExtensionDescription
  File "/home/jcfr/Projects/Slicer-Debug/Slicer-build/bin/Python/SlicerWizard/__init__.py", line 44, in <module>
    from .ExtensionWizard import ExtensionWizard
  File "/home/jcfr/Projects/Slicer-Debug/Slicer-build/bin/Python/SlicerWizard/ExtensionWizard.py", line 30, in <module>
    from .TemplateManager import TemplateManager
  File "/home/jcfr/Projects/Slicer-Debug/Slicer-build/bin/Python/SlicerWizard/TemplateManager.py", line 161
    destination = os.path.join(destination, name)
              ^
IndentationError: expected an indented block

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24455 3bd1e089-480b-0410-8dfb-8563597acbee