BUG: Fixed SegmentStatistics module not computing results
Error occurred because in certain workflows vtkSegmentationCore library was not imported:
    AttributeError: ‘vtkCommonCorePython.vtkObject’ object has no attribute ‘GetSegment’

See https://discourse.slicer.org/t/segment-statistics-does-nothing/1143/2

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26405 3bd1e089-480b-0410-8dfb-8563597acbee