COMP: Fix linux build error adding missing include in vtkMRMLPlotViewNode.cxx
This commit fixes the following build error reported when building with Qt4:

/path/to/Slicer/Libs/MRML/Core/vtkMRMLPlotViewNode.cxx: In constructor ‘vtkMRMLPlotViewNode::vtkMRMLPlotViewNode()’:
/path/to/Slicer/Libs/MRML/Core/vtkMRMLPlotViewNode.cxx:51:3: error: ‘vtkNew’ was not declared in this scope
/path/to/Slicer/Libs/MRML/Core/vtkMRMLPlotViewNode.cxx:51:21: error: expected primary-expression before ‘>’ token
/path/to/Slicer/Libs/MRML/Core/vtkMRMLPlotViewNode.cxx:51:23: error: ‘events’ was not declared in this scope

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26910 3bd1e089-480b-0410-8dfb-8563597acbee