COMP: Convert to vtkMTimeType for modified times to fix compile errors
https://gitlab.kitware.com/vtk/vtk/merge_requests/1790 ("ENH: Introduce
vtkMTimeType") adds vtkMTimeType as a typedef for vtkObject modified times,
replacing unsigned long. This commit updates Slicer to use the new type. This
fixes compile errors like:

    c:\path\to\slicer\libs\vtkteem\vtkDiffusionTensorGlyph.h(192): error C2555: 'vtkDiffusionTensorGlyph::GetMTime': overriding virtual function return type differs and is not covariant from 'vtkObject::GetMTime'