COMP: C++11 convertsion of types
error: no viable conversion from 'DiffusionTensor3DExtended<float>' to 'DiffusionTensor3DExtended<double>'

By preferring initialization to assignment this error is avoided.