COMP: vtkMRMLColorLogic: Fix windows build error related to isspace
Since the function "std::isspace" is declared in <local>, but <local>
library is not found in VS2008 STL, this commit includes "ctype.h" where
isspace() function is declared.

This commit fixes the following error:

42>45>..\..\..\..\..\Slicer-1\Libs\MRML\Logic\vtkMRMLColorLogic.cxx(1453) : error C2039: 'isspace' : is not a member of 'std'