BUG: Revert "COMP: Install pip, setuptools, wheel using whl files"
This reverts commit 26ecf484d51e4c298a76b80b3a0dec7e9c157a1d, which broke import of packages such as dicom and pydicom:

>>> import dicom
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'dicom'
>>> import pydicom
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'pydicom'

git-svn-id: http://svn.slicer.org/Slicer4/trunk@28587 3bd1e089-480b-0410-8dfb-8563597acbee