COMP: add missing vtkNew header for Qt4 build
Fixes this build error for qt4 builds (happened on both
linux and mac builds).

    [ 25%] Building CXX object Libs/MRML/DisplayableManager/CMakeFiles/MRMLDisplayableManager.dir/vtkMRMLAbstractSliceViewDisplayableManager.cxx.o
    /Users/pieper/slicer4/latest/Slicer/Libs/MRML/DisplayableManager/vtkMRMLAbstractSliceViewDisplayableManager.cxx:124:3: error: use of undeclared identifier 'vtkNew'
      vtkNew<vtkMatrix4x4> rasToXYZ;
      ^
    /Users/pieper/slicer4/latest/Slicer/Libs/MRML/DisplayableManager/vtkMRMLAbstractSliceViewDisplayableManager.cxx:124:10: error: 'vtkMatrix4x4' does not refer to a value
      vtkNew<vtkMatrix4x4> rasToXYZ;
             ^
    /Users/pieper/slicer4/latest/Slicer-superbuild/VTKv9/Rendering/Core/vtkProp.h:33:7: note: declared here
    class vtkMatrix4x4;
          ^
    /Users/pieper/slicer4/latest/Slicer/Libs/MRML/DisplayableManager/vtkMRMLAbstractSliceViewDisplayableManager.cxx:124:24: error: use of undeclared identifier 'rasToXYZ'
      vtkNew<vtkMatrix4x4> rasToXYZ;
                           ^
    /Users/pieper/slicer4/latest/Slicer/Libs/MRML/DisplayableManager/vtkMRMLAbstractSliceViewDisplayableManager.cxx:125:49: error: use of undeclared identifier 'rasToXYZ'

From: Steve Pieper <pieper@isomics.com>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@27134 3bd1e089-480b-0410-8dfb-8563597acbee