BUG: Fix upload of macOS extensions to the Girder-based extension manager server
This commit fixes the error reported below ensuring the python client
is running with the proper local (en_US.UTF-8 instead of C) on the macOS
factory machine.

This is required because the build script are executed using cronjob that only
has a minimal environment where the LANG= variable is not set to UTF-8.

References:

  http://click.pocoo.org/6/python3/#python-3-surrogate-handling

Error:

  RuntimeError: Click will abort further execution because Python 3 was
  configured to use ASCII as encoding for the environment.
  Consult http://click.pocoo.org/python3/for mitigation steps.

  This system lists a couple of UTF-8 supporting locales that
  you can pick from.  The following suitable locales where
  discovered: [...]

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26938 3bd1e089-480b-0410-8dfb-8563597acbee