COMP: Update SlicerExecutionModel to include support for ITK+ExternalModule
This commit updates the SlicerExecutionModel so that it can build
against the version of ITK including ExternalModule support introduced
in the previous commit. It will fix the following error:

Linking CXX executable bin/GenerateCLP
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_ParserCreate'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_GetErrorCode'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_SetUserData'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_GetSpecifiedAttributeCount'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_GetCurrentLineNumber'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_ErrorString'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_ParserFree'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_SetElementHandler'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_Parse'
../ModuleDescriptionParser/bin/libModuleDescriptionParser.so: undefined reference to `XML_SetCharacterDataHandler'
collect2: error: ld returned 1 exit status


$ git shortlog 608c7b0..311eff9 --no-merges
Hans Johnson (1):
      COMP: Add missing link dependancy for ITKExpat

Lucas Gandel (5):
      ENH: Support submission of test results on CDash
      ENH: Add Docker Test file
      ENH: Reorganize docker files to support testing against multiple ITK version
      ENH: Add support for continuous integration testing using CircleCI
      ENH: Add Relevant BUILDNAME for CDash submission

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24691 3bd1e089-480b-0410-8dfb-8563597acbee