COMP: Fix regression in VTK python wrapping built using VTK7
This commit fixes a regression introduced in previous commit r26313 (COMP: Fix
VTK python wrapping of extension built against Slicer with VTK8)

It ensures that VTK_WRAP_INCLUDE_DIRS is also set when building
with vTK <= 8.

It fixes the following error reported when building EMSegment python
wrappers:

```
/path/to/Slicer-build/Slicer-build/Modules/Remote/EMSegment/Qt/Logic/vtkImageEMLocalGenericClassPython.cxx: In function ‘PyObject* PyvtkImageEMLocalGenericClass_SetProbDataPtr(PyObject*, PyObject*)’:
/path/to/Slicer-build/Slicer-build/Modules/Remote/EMSegment/Qt/Logic/vtkImageEMLocalGenericClassPython.cxx:262:11: error: ‘class vtkImageEMLocalGenericClass’ has no member named ‘SetProbDataPtr’
       op->SetProbDataPtr(temp0);
           ^
/path/to/Slicer-build/Slicer-build/Modules/Remote/EMSegment/Qt/Logic/vtkImageEMLocalGenericClassPython.cxx:266:40: error: ‘class vtkImageEMLocalGenericClass’ has no member named ‘SetProbDataPtr’
       op->vtkImageEMLocalGenericClass::SetProbDataPtr(temp0);
                                        ^
```

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26314 3bd1e089-480b-0410-8dfb-8563597acbee