COMP: Update ITKv4 to fix MINC build error using redhat devtoolset 2
This commit updates ITK and fix an error reported when building
Slicer using redhat toolset 2 on CircleCI.

Details:

8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---
commit Slicer/ITK@3cc1a24
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Wed May 17 03:52:36 2017 -0400

    COMP: libminc: Define _GNU_SOURCE to enable C99 extension during introspection

    This commit addresses failure to detect "round" function on
    compiler like g++ 4.8.2 provided by redhat devtoolset 2 [1].

    More specifically, since the macro __USE_ISOC99 wasn't defined, function
    "round" declared in "mathcalls.h" (itself included from "math.h") wasn't
    found during introspection.

    Defining _GNU_SOURCE allows to enable c99. See features.h for more details.

    Error fixed by this commit is the following:

    /path/to/ITKv4/Modules/ThirdParty/MINC/src/libminc/libsrc2/hyper.c:64:1: error: redefinition of ‘round’
     round(double x)
     ^

    and it is reproducible using docker-centos-build [2].

    CMake macro was adapated from python-cmake-buildsystem [3]

    [1] https://access.redhat.com/documentation/en-US/Red_Hat_Developer_Toolset/2/html/2.0_Release_Notes/DTS2.0_Release.html
    [2] https://github.com/thewtex/docker-centos-build
    [3] https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/blob/d0f47193837db6ad9e08bc99617276d4a24687c3/cmake/ConfigureChecks.cmake#L415
8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---8<---

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26017 3bd1e089-480b-0410-8dfb-8563597acbee