BUG: Ignore user site python packages.
This commit will fix error like the one reported below where PYTHONPATH
was prepended with system locations because it found packages in user
home folder.

List of folders that will NOT be prepended after env. variable "PYTHONNOUSERSITE"
is set to 1 are documented here:

  https://docs.python.org/2/library/site.html#site.USER_SITE

Error:

  File "setup.py", line 19, in <module>
    exec(init_file.read(), command_ns)
  File "<string>", line 11, in <module>
  File "/home/lucas/Projects/Slicer/Slicer-superbuild/python-setuptools/setuptools/__init__.py", line 12, in <module>
    from setuptools.extension import Extension
  File "/home/lucas/Projects/Slicer/Slicer-superbuild/python-setuptools/setuptools/extension.py", line 7, in <module>
    from setuptools.dist import _get_unpatched
  File "/home/lucas/Projects/Slicer/Slicer-superbuild/python-setuptools/setuptools/dist.py", line 16, in <module>
    from setuptools.depends import Require
  File "/home/lucas/Projects/Slicer/Slicer-superbuild/python-setuptools/setuptools/depends.py", line 6, in <module>
    from setuptools import compat
  File "/home/lucas/Projects/Slicer/Slicer-superbuild/python-setuptools/setuptools/compat.py", line 19, in <module>
    import httplib
  File "/usr/lib/python2.7/httplib.py", line 71, in <module>
    import socket
  File "/usr/lib/python2.7/socket.py", line 68, in <module>
    from _ssl import \
ImportError: cannot import name RAND_egd


Co-authored-by: Lucas Gandel <lucas.gandel@kitware.com>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@25203 3bd1e089-480b-0410-8dfb-8563597acbee