COMP: Update BRAINSTools and fix itkExceptionObject include error introduced by ITK update
This commit fixes errors like the following introduced by r28458 (ENH: Update
ITK and use upstream repo):

  C:\e\ScD\ITK\Modules\Core\Common\include\itkExceptionObject.h(19): fatal error C1189: #error:  "Do not include itkExceptionObject.h directly,  incl
ude itkMacro.h instead." [C:\e\ScD\Slicer-build\Libs\MRML\Core\MRMLCore.vcxproj] [C:\e\ScD\Slicer.vcxproj]

Specific ITK commit introducing the regression is
InsightSoftwareConsortium/ITK@ad0007e88 (ENH: Replace ExceptionObjects with itkExceptionMacro. )
See https://github.com/InsightSoftwareConsortium/ITK/commit/ad0007e8868e4e51825c2f56a1e59a56bf99b69e


List of BRAINSTools changes:

$ git shortlog 4a4b52f6a..d0e6c01c --no-merges
Hans J. Johnson (79):
      ENH: Support documents for better code formatting conformance
      ENH: Remove unused file accidently committed.
      ENH: Remove unwrapimage from pipeline
      ENH: Clean up IPD range checking code.
      ENH: Refactor to isolate image resampling from Eye points
      ENH: Remove m_Ipd and m_RotAng as unnecessary class variables
      ENH: Separate computing transform from applying resampling.
      ENH: Refactoring to identify parity between manual and automated lmk ACPC
      ENH: Modify auto workup so that input landmark files are found
      ENH: Fix naming of variables to the expected outputs as visually verified
      STYLE: Address clang tidy identified issues.
      STYLE: Move all landmark settings together.
      STYLE: Improve function name to include space information.
      STYLE: Prefer to use cmake fixtures capabilities for testing dependancies
      DOC: Variable namings incomplete, or incorrect for the intended purpose
      DOC: Improve documentation and default values for forced landmarks
      ENH: Simplify logic for addressing RAS and LPS landmark definitions.
      DOC: More renaming for clarity.
      STYLE: Prefere initialization to assignment
      BUG: Put a hard limit on threads for BCD
      STYLE: Remove unused code that was never executed.
      STYLE: Changed name for landmarks that will eventually be constant
      ENH: Set initial landmarks as a landmark list
      ENH: Make function static and pass inputs required in
      ENH: Make const and non-const aliases to the orig_lmks
      ENH: Created another alias to track values of multi-use maps.
      ENH: Make class variable local to the one function is used for exclusively.
      ENH: Make local variables for temporary values of MSP centering.
      ENH: Strip more useless code to identify logic more clearly.
      ENH: Simplify code by using names consistently, and co-locating variables
      ENH: Simplify checking for key in map.
      DOC: Add diagnostic messages with landmark name.
      DOC: Silence debugging messages.
      ENH: Collapse complexity of code to combine two if hasUserForced*Point conditionals
      ENH: Collapse complexity of code to combine two if hasUserForced*Point conditionals
      BUG: Decouple original landmarks from updated landmarks in orig space!
      ENH: Remove separate landmark point variable, use landmark listing
      STYLE: Change variable name to match calling environment naming
      ENH: Test that forced landmark points are preserved.
      STYLE: Remove commented out code from repo.
      STYLE: Organize code and remove commented out sections.
      ENH: Add missing space in diagnostic message.
      STYLE: Remove alias variables, and make direct queries to existence.
      STYLE: Remove aliased variable name using image as it's own mask.
      STYLE: Remove aliased variable for the same concept of holding the msp_lmk points
      ENH: Improve diagnostic messaging for writing files.
      ENH: Improve setting of the CenterOfHeadMass to be more clear
      STYLE: Use name consistently for landmark indexes.
      STYLE: Use enhanced for loop for improved maintenance
      ENH: Disable DCMTK by default for superbuilds.
      ENH: Localizing msp variables for easier refactoring.
      DOC: Improve diagnostic of landmark compare program
      STYLE: Improve variable name for tracking down redundant variable aliases
      STYLE: Improve variable name of local eye variable aliases
      DOC: Added todo notes.
      STYLE: minimize some TODO items as less relevant.
      ENH: Make landmark weights maps consistent as double values.
      ENH: Add tolerance weights per landmark
      ENH: Move separate landmark processing to landmark lists
      ENH: Remove TODO and dead code
      BUG: Fix type matching for landmark weights type.
      ENH: Change diagnostic message to note
      ENH: Convert TODO: to INFO: for old code review comments.
      ENH: Ignore temporary .ExternalData files.
      ENH: Update ExternalData processing to use SHA512 hashes
      COMP: Link building DCMTK to dependant tools.
      STYLE: Remove #  if ITK_VERSION_MAJOR >= 5
      ENH: Need to graft the output from the AccumulatorImage.
      ENH: Fix BRAINSEyeDetectorTest_T1 test.
      WIP: Partial update of test data.
      COMP: Do not include itkExceptionMacro.h
      ENH: Revert corrupt data file, fix failing test
      ENH: Update ITK and ANTs to latest version.
      ENH: Update testing data for new BCD.
      ENH: Add missing header.
      COMP: Remove direct inclusion of itkExceptionObject.h
      COMP: Build into separate directories based on build type
      ENH: Optimize build robustness and reduce ANTs build time.
      ENH: Fix order of variable setting

Regina EY Kim (1):
      ENH: Add an input option for input file


Co-authored-by: Csaba Pinter <csaba.pinter@queensu.ca>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@28463 3bd1e089-480b-0410-8dfb-8563597acbee