COMP: Update python to fix linuxaudiodev build error
This commit fixes the version handling and prevents the flag -std=c99
from being used. See python-cmake-buildsystem/python-cmake-buildsystem@3e00b46
and python-cmake-buildsystem/python-cmake-buildsystem@5530813

It fixes error like this one:

  linuxaudiodev.c:69:17: error: ‘AFMT_MU_LAW’ undeclared here (not in a function)
     {  8,       AFMT_MU_LAW, "logarithmic mu-law 8-bit audio" },


List of changes:

$ git shortlog 3e0e336..16d41fe --no-merges
Jean-Christophe Fillion-Robin (2):
      cmake: Use PY_VERSION instead of PYTHON_VERSION
      cmake: Ensure PYTHON_VERSION cache variable is up-to-date

git-svn-id: http://svn.slicer.org/Slicer4/trunk@27119 3bd1e089-480b-0410-8dfb-8563597acbee