COMP: qMRMLTableView: Fix unix build error using function instead of macro
This commit fixes error introduced in r24783 (ENH: Added support for Tables)
similar to the following one:

/path/to/Slicer/Libs/MRML/Widgets/qMRMLTableView.cxx:217:44: error: macro "VERIFY_TABLE_MODEL_AND_NODE" requires 2 arguments, but only 1 given
   VERIFY_TABLE_MODEL_AND_NODE(setTransposed);
                                            ^