ENH: Fixes #3549. Import scripted module as python module
This will allow each scripted module to defined top-level variables that
will not clobber each other.

For example, if we consider these two modules:

8<----8<----8<----8<----8<----8<----8<----8<----
File: ModuleA.py

FOO = 1

class ModuleA(ScriptedLoadableModule):
  def __init__(self, parent):
    ModuleA.__init__(self, parent)
    [...]
  def doSomething(self):
    if FOO == 1:
      [...]
    else:
      [...]
8<----8<----8<----8<----8<----8<----8<----8<----

8<----8<----8<----8<----8<----8<----8<----8<----
File: ModuleB.py

FOO = 2

class ModuleB(ScriptedLoadableModule):
  def __init__(self, parent):
    ModuleB.__init__(self, parent)
    [...]
  def doSomething(self):
    if FOO == 1:
      [...]
    else:
      [...]
8<----8<----8<----8<----8<----8<----8<----8<----

Assuming ModuleA, and then ModuleB are imported. Before this commit,
both scripts were executed in the __main__ scope and FOO variable would
have the value associated with the last imported module.

After this commit, both module will see their own copy of the FOO
variable with the expected value.

It also avoid the hack when we explicitly save/set/restore
both "__name__" and "__file__" variable.

Changes to "DICOMScalarVolumePlugin" fixes the test failing test
"py_RSNAVisTutorial" and "py_SubjectHierarchyGenericSelfTest". It basically
fixes the following error by ensuring all object are imported:

//--------------
test_SubjectHierarchyGenericSelfTest_FullTest1 (SubjectHierarchyGenericSelfTest.SubjectHierarchyGenericSelfTestTest) ... Traceback (most recent call last):
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DICOMLib/DICOMWidgets.py", line 615, in getLoadablesFromFileLists
    loadablesByPlugin[plugin] = plugin.examineForImport(fileLists)
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 47, in examineForImport
    loadablesForFiles = self.examineFiles(files)
  File "/path/to/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DICOMScalarVolumePlugin.py", line 71, in examineFiles
    loadable = DICOMLib.DICOMLoadable()
NameError: global name 'DICOMLib' is not defined
//--------------