COMP: Fix VTK external project to work correctly with Ninja generator
Use the variable 'CMAKE_MAKE_PROGRAM' instead of the undocumented variable
MAKECOMMAND.

For more details referers to CMake commits kitware/CMake@4ac75fdf [1] and
kitware/CMake@4cce44b [2]

This is know to work with:
 - Ninja 1.4.0
 - CMake 2.8.12.1

[1] http://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=4ac75fdf
[2] http://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=4cce44b

The error was:

// ---------------
FAILED: cd /home/jchris/Projects/SarrpTPS-SuperBuild-Release-Qt485-N/Slicer-build/VTK-build && /home/jchris/Support/cmake-2.8.11.2/bin/cmake -DMAKE_COMMAND= -P /home/jchris/Projects/SarrpTPS-SuperBuild-Release-Qt485-N/Slicer-build/VTK_build_step.cmake && /home/jchris/Support/cmake-2.8.11.2/bin/cmake -E touch /home/jchris/Projects/SarrpTPS-SuperBuild-Release-Qt485-N/Slicer-build/VTK-prefix/src/VTK-stamp/VTK-build
CMake Error at /home/jchris/Projects/SarrpTPS-SuperBuild-Release-Qt485-N/Slicer-build/VTK_build_step.cmake:5 (message):
  error: MAKE_COMMAND is not set !
// ---------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@22838 3bd1e089-480b-0410-8dfb-8563597acbee