BUG: Perform performPostModuleDiscoveryTasks only if DICOM is loaded
This commit ensures the function is called if both startup is completed and
if all DICOM module dependencies have been successfully loaded.

Failing to do so only systematically call the performPostModuleDiscoveryTasks
and would try to call functions on object not initialized.

For example:

  $ ./Slicer "--testing" --disable-cli-modules --disable-loadable-modules

  [...]

  Traceback (most recent call last):
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOM.py", line 116, in performPostModuleDiscoveryTasks
      self.setDetailsPopup(DICOMWidget.getSavedDICOMDetailsWidgetType()())
    File "/path/to/Slicer-SuperBuild/Slicer-build/lib/Slicer-4.11/qt-scripted-modules/DICOM.py", line 164, in setDetailsPopup
      self.viewFactory.setWidget(self.viewWidget)
  AttributeError: 'DICOM' object has no attribute 'viewFactory'

git-svn-id: http://svn.slicer.org/Slicer4/trunk@28483 3bd1e089-480b-0410-8dfb-8563597acbee