ENH: Do no disable the picking in 2D since the widget is never pickable
This prevent the following error to appear when using 2D projection:

ERROR: In c:\d\p\slicer-440-package\vtkv6\interaction\widgets\vtkWidgetRepresentation.h, line 176
vtkPointHandleRepresentation2D (0000000010537080): Subclass should allow enable/disable picking