COMP: Add missing header when using QVTKOpenGLWidget
Same fix than #987 but for all tests.

Missing header when `Slicer_VTK_USE_QVTKOPENGLWIDGET` is defined.

Tested using VTKv9 from this branch:
https://github.com/phcerdan/VTK/tree/slicer-v9.0.0-2018-07-06-982ec1c561

Solve error:
```bash
In file included from
/Software/Shape/SALT/build/slicersources-src/Libs/MRML/Widgets/Testing/qMRMLDisplayNodeWidgetTest1.cxx:37:
/Software/Shape/SALT/build/VTKv9/GUISupport/Qt/QVTKOpenGLWidget.h:23:7:
note: forward declaration of ‘class QSurfaceFormat’
 class QSurfaceFormat;
        ^~~~~~~~~~~~~~
        /Software/Shape/SALT/build/slicersources-src/Libs/MRML/Widgets/Testing/qMRMLDisplayNodeWidgetTest1.cxx:48:19:
        error: incomplete type ‘QSurfaceFormat’ used in nested name
        specifier
           QSurfaceFormat::setDefaultFormat(format);
```