BUG: Legacy module OtsuThresholdImageFilter needed by EMSegment. Issue #3815
This commit fixes a regression introduced by r23598 which removed
the source of OtsuThresholdImageFilter. This ensures EMSegment will
work as expected by integrating the source of the CLI as a
remote module [1].

[1] http://wiki.slicer.org/slicerWiki/index.php/Documentation/Nightly/Developers/Build_system/Remote_Module

For future reference, the EMSegment test
"EMSeg_SlicerCommonInterfaceTestGeneral" was failing with:

// ---------------
[...]
Test 7 : PreprocessingBiasFieldCorrection
ERROR: In /home/kitware/Dashboards/Nightly/Slicer-0-build/EMSegment/vtkSlicerCommonInterface.cxx, line 609
vtkSlicerCommonInterface (0x226d940): Could not find path to OtsuThresholdImageFilter

ERROR: In /home/kitware/Dashboards/Nightly/Slicer-0/Libs/MRML/Core/vtkMRMLVolumeArchetypeStorageNode.cxx, line 367
vtkMRMLVolumeArchetypeStorageNode (0x235fd00): ReadData: Cannot read file as a volume of type Volume[fullName = /tmp/EMSD1388245976wJ71mE/mask.nrrd]
    Number of files listed in the node = 0.
    File reader says it was able to read 0 files.
    File reader used the archetype file name of /tmp/EMSD1388245976wJ71mE/mask.nrrd []
[...]
// ---------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23611 3bd1e089-480b-0410-8dfb-8563597acbee