BUG: Fix slicerExtensionWizard in MacOSX package. Fixes #3750
This commit fixes the following error:

//-----
 /Volumes/Slicer-4.3.1-2014-06-26-macosx-amd64/Slicer.app/Contents/bin/slicerExtensionWizard: line 11: /Volumes/Slicer-4.3.1-2014-06-26-macosx-amd64/Slicer.app/Contents/bin/../Slicer: No such file or directory
Traceback (most recent call last):
 File "/Volumes/Slicer-4.3.1-2014-06-26-macosx-amd64/Slicer.app/Contents/bin/../libexec/Slicer-4.3/ExtensionWizard.py", line 6, in <module>
   from SlicerWizard import ExtensionWizard
ImportError: No module named SlicerWizard
//-----

Instead of relying on Slicer launcher that is not available on MacOSX,
the SlicerPython launcher available on all platform is configured with
the path to the SlicerWizard module and the slicerExtensionWizard script
is updated to use it.

Co-authored-by: Peter Savadjiev <petersv@bwh.harvard.edu>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23390 3bd1e089-480b-0410-8dfb-8563597acbee