COMP: Fix superbuild extension template build error
Following r21776[1], the description hasn't been renamed whereas
the associated directory was. This was preventing the
testing extensions from being built successfully. See error reported
below.

This commit rename the description file.

[1] http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=21776


// -------------
[...]
-- Configuring extension: SuperBuildLoadableExtensionTemplate
.CMake Error at C:/D/Support/CMake 2.8.10.2/share/cmake-2.8/Modules/ExternalProject.cmake:1334 (message):
  error: no download info for 'SuperBuildLoadableExtensionTemplate' -- please
  specify existing/non-empty SOURCE_DIR or one of URL, CVS_REPOSITORY and
  CVS_MODULE, SVN_REPOSITORY, GIT_REPOSITORY, HG_REPOSITORY or
  DOWNLOAD_COMMAND
Call Stack (most recent call first):
  C:/D/Support/CMake 2.8.10.2/share/cmake-2.8/Modules/ExternalProject.cmake:1699 (_ep_add_download_command)
  SlicerBlockBuildPackageAndUploadExtensions.cmake:156 (ExternalProject_Add)
  CMakeLists.txt:85 (include)


-- Configuring incomplete, errors occurred!
[...]
//---------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@22045 3bd1e089-480b-0410-8dfb-8563597acbee