COMP: Fix setting of Slicer_SUPERBUILD_DIR for Slicer Custom application
This commit updates the build system so that it:
* ensures that python files are packaged
* an error is reported if "PYTHON_DIR" variable is not set in SlicerBlockInstallPython

Symptom leading to this fix was the following error reported when
starting the application:

  ImportError: No module named site

Co-authored-by: Dzenan Zukic <dzenan.zukic@kitware.com>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26683 3bd1e089-480b-0410-8dfb-8563597acbee