COMP: Update ITKv4 to fix MacOSX compilation issue.
//------------------
commit 5f95aa6712c508a637a12faaea119d35e574208c
Author: Bradley Lowekamp <blowekamp@mail.nih.gov>
Date:   Thu Jun 25 10:25:11 2015 -0400

    COMP: Explicitly export SingleValuedNonLinearVnlOptimizerv4

    Address the following linking issue:

    Undefined symbols for architecture x86_64:
      "typeinfo for itk::SingleValuedNonLinearVnlOptimizerv4", referenced
      from:
          typeinfo for itk::LBFGSOptimizerBasev4<vnl_lbfgsb> in
          libSimpleITKRegistration-0.9.a(sitkImageRegistrationMethod_CreateOptimizer.cxx.o)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see
    invocation)
//------------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24361 3bd1e089-480b-0410-8dfb-8563597acbee