COMP: Add missing headers.
Solve incomplete type errors when using latest VTKv9:
982ec1c561868f3e2442d11df0c44eaea1e56834

```
Software/Slicer/Slicer-src/Base/QTApp/qSlicerApplicationHelper.cxx: In static member function ‘static void qSlicerApplicationHelper::preInitializeApplication(const char*, ctkProxyStyle*)’:
Software/Slicer/Slicer-src/Base/QTApp/qSlicerApplicationHelper.cxx:98:18: error: variable ‘QSurfaceFormat format’ has initializer but incomplete type
   QSurfaceFormat format = QVTKOpenGLWidget::defaultFormat();
                  ^~~~~~
Software/Slicer/Slicer-src/Base/QTApp/qSlicerApplicationHelper.cxx:98:59: error: invalid use of incomplete type ‘class QSurfaceFormat’
   QSurfaceFormat format = QVTKOpenGLWidget::defaultFormat();
                                                           ^
In file included from Software/Slicer/Slicer-src/Base/QTApp/qSlicerApplicationHelper.cxx:59:
Software/Slicer/build-relwithdebinfo/VTKv9/GUISupport/Qt/QVTKOpenGLWidget.h:23:7: note: forward declaration of ‘class QSurfaceFormat’
 class QSurfaceFormat;
       ^~~~~~~~~~~~~~
Software/Slicer/Slicer-src/Base/QTApp/qSlicerApplicationHelper.cxx:100:19: error: incomplete type ‘QSurfaceFormat’ used in nested name specifier
   QSurfaceFormat::setDefaultFormat(format);
```