BUG: Fix SliceViewAnnotations AttributeError happening on closing Slicer
This commit fixes the following error introducing a weak pointer to keep
track of the layout manager.

8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----
File "/home/jcfr/Projects/Slicer-Debug/Slicer-build/lib/Slicer-4.4/qt-scripted-modules/DataProbeLib/SliceViewAnnotations.py", line 628, in updateCornerAnnotations
  sliceViewNames = slicer.app.layoutManager().sliceViewNames()
AttributeError: 'NoneType' object has no attribute 'sliceViewNames'
8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----8<----

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24238 3bd1e089-480b-0410-8dfb-8563597acbee