COMP: Support building in RelWithDebInfo configuration on Windows
This commit fixes build errors when building in the RelWithDebInfo configuration
on Windows. Previously, projects that use OpenSSL_DIR would fail to find the
OpenSSL headers because only 'Debug' and 'Release' directories--not
'RelWithDebInfo'--are provided by the precompiled OpenSSL binaries.

An example error is:

    10>C:\S\R\Python-2.7.11\Modules\_hashopenssl.c(39): fatal error C1083: Cannot open include file: 'openssl/evp.h': No such file or directory

Fixes http://www.na-mic.org/Mantis/view.php?id=4058.