COMP: Update setuptools to avoid future update conflict related to setup.cfg
This commit will avoid error like the following:

```
error: Your local changes to the following files would be overwritten by checkout:
    setup.cfg
Please, commit your changes or stash them before you can switch branches.
Aborting
```

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26477 3bd1e089-480b-0410-8dfb-8563597acbee