COMP: ExtractSkeleton: Fix build error reported on Linux
This commit fixes the following error:

/path/to/Slicer/Modules/CLI/ExtractSkeleton/SkelGraph.cxx:409:107: error: no matching function for call to ‘find(std::deque<int>::iterator, std::deque<int>::iterator, int&)’
  if (std::find(branch.end_2_neighbors.begin(), branch.end_2_neighbors.end(), previousBranch->branchID) != branch.end_2_neighbors.end())
                                                                                                      ^

The build error was introduced in r26843 (BUG: Fixed centerline points computation
in ExtractSkeleton module)

Suggested-by: Andras Lasso <lasso@queensu.ca>
Tested-by: Steve Pieper <pieper@bwh.harvard.edu>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26857 3bd1e089-480b-0410-8dfb-8563597acbee